"""Regenerate the Dictionaries table in README.md from arabterm.db.

Replaces the content between the markers:
    <!-- DICTIONARIES_TABLE_START ... -->
    <!-- DICTIONARIES_TABLE_END -->

Sort order: most-recently-added first (by `created_at` desc, then `id` desc
as a stable tie-break).
"""

from __future__ import annotations

import re
from pathlib import Path

from arabterm.sqlite_models import Dictionary, get_sqlite_connection

REPO_ROOT = Path(__file__).resolve().parents[2]
README = REPO_ROOT / "README.md"
START = "<!-- DICTIONARIES_TABLE_START"
END = "<!-- DICTIONARIES_TABLE_END -->"
WIKIDATA_URL = "https://www.wikidata.org/wiki/"


def _en_fr_cell(en: str | None, fr: str | None) -> str:
    en = (en or "").strip()
    fr = (fr or "").strip()
    if en and fr and en != fr:
        return f"{en}<br />{fr}"
    return en or fr


def _wikidata_cell(qid: str | None) -> str:
    qid = (qid or "").strip()
    return f"[{qid}]({WIKIDATA_URL}{qid})" if qid else ""


def build_table(session) -> str:
    dicts = (
        session.query(Dictionary)
        .order_by(Dictionary.created_at.desc(), Dictionary.id.desc())
        .all()
    )
    lines = [
        f"{START} — auto-generated by `make readme`; do not edit by hand -->",
        "| العربية | English / Français | Entries | Wikidata |",
        "|:---|:---|---:|:---:|",
    ]
    for d in dicts:
        lines.append(
            f"| {(d.name_arabic or '').strip()} "
            f"| {_en_fr_cell(d.name_english, d.name_french)} "
            f"| {d.nbr_entries or 0} "
            f"| {_wikidata_cell(d.wikidata_id)} |"
        )
    lines.append(END)
    return "\n".join(lines)


def main() -> None:
    with get_sqlite_connection() as session:
        new_block = build_table(session)

    text = README.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(text):
        raise SystemExit(
            f"Markers not found in {README}. Expected {START!r} … {END!r}."
        )
    new_text = pattern.sub(new_block, text)
    if new_text == text:
        print(f"README.md already up to date ({README})")
        return
    README.write_text(new_text, encoding="utf-8")
    print(f"Updated dictionaries table in {README}")


if __name__ == "__main__":
    main()
